-- Add additional seed notifications for testing
INSERT INTO notifications (notification_type, title, message, reference_id, is_read, created_at) VALUES
('new_paid_delivery', 'New Paid Delivery', 'A new delivery for Women Fashion Dress has been paid and is awaiting assignment.', (SELECT id FROM deliveries ORDER BY created_at DESC LIMIT 1 OFFSET 1), false, NOW() - INTERVAL '25 minutes'),
('failed_delivery', 'Delivery Failed', 'Delivery failed: Wrong address provided by customer.', (SELECT id FROM deliveries ORDER BY created_at DESC LIMIT 1 OFFSET 1), true, NOW() - INTERVAL '4 hours'),
('expense_submission', 'Expense Approved', 'Fuel expense for 12,000 FCFA has been approved for Pierre Nkongo.', (SELECT id FROM carrier_expenses ORDER BY created_at DESC LIMIT 1 OFFSET 2), false, NOW() - INTERVAL '30 minutes'),
('new_merchant_registration', 'New Merchant Registered', 'A new merchant Mvog-Mbi Market has completed registration.', (SELECT id FROM merchants ORDER BY created_at DESC LIMIT 1 OFFSET 2), false, NOW() - INTERVAL '2 hours'),
('delivery_assigned', 'Delivery Picked Up', 'Pharmacy delivery has been picked up by Pierre Nkongo and is now in transit.', (SELECT id FROM deliveries ORDER BY created_at DESC LIMIT 1 OFFSET 3), false, NOW() - INTERVAL '45 minutes'),
('new_carrier_registration', 'New Carrier Registration', 'Marie Atangana has completed carrier registration and is awaiting approval.', (SELECT id FROM carriers ORDER BY created_at DESC LIMIT 1 OFFSET 2), false, NOW() - INTERVAL '1 hour'),
('new_carrier_registration', 'New Carrier Registration', 'Paul Essama has completed carrier registration and is awaiting approval.', (SELECT id FROM carriers ORDER BY created_at DESC LIMIT 1 OFFSET 3), true, NOW() - INTERVAL '5 hours'),
('new_paid_delivery', 'New Paid Delivery', 'A new delivery for ACER Laptop has been paid and is awaiting assignment.', (SELECT id FROM deliveries ORDER BY created_at DESC LIMIT 1), false, NOW() - INTERVAL '20 minutes');